### ISSUE TITLE
Can not be configured use .commit instead .flush

### ISSUE THREAD

**Issue by galetskiav** [absent1706/sqlalchemy-mixins#53] opened 2020-11-25 06:43 UTC
Now in project after Model.create(name="zxc") i need use db.session.commit().

**Comment by aurthurm** [comment] 2020-11-30 10:24
Override the .save() in your base class that inherits from the allfeature mixin like 

```
def save(self):
        """Saves the updated model to the current entity db.
        """
        self.session.add(self)
        self.session.flush()
        self.session.commit()
        return self
```

**Comment by Shashwat986** [comment] 2020-12-11 13:26
While this works, we will need to do the same thing for create as well, which is annoying, to say the least, and increases complexity

**Comment by Shashwat986** [comment] 2020-12-11 14:00
using `commit()` explicitly caused some issues with failed SQL queries dirtying the connection, so I've done this:

```py
    def save(self):
        try:
            super().save()
            self.session.commit()
        except:
            self.session.rollback()
            raise

    def delete(self):
        try:
            super().delete()
            self.session.commit()
        except:
            self.session.rollback()
            raise
```

**Comment by FinnWoelm** [comment] 2021-10-02 15:08
> using `commit()` explicitly caused some issues with failed SQL queries dirtying the connection, so I've done this:
> 
> ```python
>     def save(self):
>         try:
>             super().save()
>             self.session.commit()
>         except:
>             self.session.rollback()
>             raise
> 
>     def delete(self):
>         try:
>             super().delete()
>             self.session.commit()
>         except:
>             self.session.rollback()
>             raise
> ```
> 
> I'm not sure whether using `except` is fine or not. It works for me, but it might be a better idea to explicitly catch `sqlalchemy.exc.DBAPIError`

One small addition to the excellent `save` method above: We should `return self` at the end to mirror the `save` method from this package. See:
https://github.com/absent1706/sqlalchemy-mixins/blob/d6dc3bdb0eb6660228d15d5482878090053ebf8d/sqlalchemy_mixins/activerecord.py#L31

 Otherwise, you will not get the new instance returned when calling `User.create()`, for example.

**Comment by michaelbukachi** [comment] 2021-10-02 15:30
One of the requirements for using this library is foregoing the use of explicitly `commit`. Do you have a specific use case as to why you need to call it explicitly?

**Comment by Shashwat986** [comment] 2021-10-02 17:02
I think the issue is that in the `Class.create(...)` scenario, the DB entry is not being automatically created. Since this bug is still open, the easier solution is to overwrite the `save` method in the base class, so that we can continue to use the library without explicitly calling `commit`.

**Comment by michaelbukachi** [comment] 2021-10-02 17:54
@Shashwat986 do you mind creating a PR. I can get this merged really quickly.

**Comment by Shashwat986** [comment] 2021-10-02 18:19
Sure. I'll get working on it. Thanks!

**Comment by ZhymabekRoman** [comment] 2021-10-03 00:42
Lol, I solved this problem by adding the autocommit parameter during session creation:
`session = scoped_session(sessionmaker(bind=engine, autocommit=True))`

**Comment by deajan** [comment] 2022-11-23 21:24
Autocommit has been deprecated with SQLAlchemy 1.4, and produces error `error Engine.connect() got an unexpected keyword argument 'close_with_result'` when used with `session = scoped_session(sessionmaker(bind=engine, autocommit=True))` or with `session = Session(engine, autocommit=True)`

Recent SQLAlchemy 1.4 (and soon to be 2.0) session syntax has a [context](https://docs.sqlalchemy.org/en/20/orm/session_transaction.html), ie:
```
 Session = sessionmaker(engine)

with Session() as session:
    with session.begin():
        session.add(some_object)
    # commits

# closes the Session
```

I think ActiveRecordMixin should itself have the autocommit flag, like in a class variable `__autocommit__ = True`, or even detect what kind of session has been passed, and use contextmanager when a sessionmaker object is passed.

What do you guys think ?

**Comment by ethagnawl** [comment] 2023-03-13 19:51
Hello, again, @deajan! I feel like I'm shadowing you between this project and SQLModel. grin

Did you ever come up with a clean way of doing what you'd outlined above?

**Comment by michaelbukachi** [comment] 2023-03-13 23:28
@deajan Work has started on [SQLALchemy](https://github.com/absent1706/sqlalchemy-mixins/pull/95) support. The objective will be to try to maintain the same behaviour as much a the underlying library is changing cc @ethagnawl

**Closed** 2023-03-13 23:30 UTC

**Comment by ethagnawl** [comment] 2023-03-13 23:40
That's great news, @michaelbukachi! I'll follow along via that PR. I'm happy to help test when the time comes.

**Comment by michaelbukachi** [comment] 2023-03-15 00:01
@ethagnawl You can now test #95

**Comment by ethagnawl** [comment] 2023-03-15 00:13
I will give it a try tomorrow. Thanks, @michaelbukachi! :raised_hands:

**Comment by ethagnawl** [comment] 2023-03-15 20:32
Arg. SQLModel isn't compatible with SQLAlchemy 2 yet. I'll have to setup a new project to test.
